import graphics
from graphics import *
import time
win=GraphWin('HW#2', 400, 400)
center=Point(200,200)
circ=Circle(center,90)
circ.setFill('yellow')
circ.draw(win)
time.sleep(1)
center=Point(200,200)
circ=Circle(center,90)
circ.setOutline('red')
circ.setOutline('red')
circ.draw(win)
time.sleep(1)
center=Point(200,200)
circ=Circle(center,90)
circ.setOutline('blue')
circ.setOutline('blue')
circ.draw(win)
time.sleep(1)
center=Point(200,200)
circ=Circle(center,90)
circ.setOutline('black')
circ.draw(win)
time.sleep(1)
center=Point(200,200)
circ=Circle(center,90)
circ.setOutline('white')
circ.draw(win)
